### ISSUE TITLE
DataBase and GUI connection

### ISSUE THREAD

**Issue by Fjohnpaul** [IgnacioFlores1500/RFID-Project#6]
Since the GUI file name was changed since moving into an entire folder, wouldn't we need to change imports in database code?

**Comment by IgnacioFlores1500** [comment]
You are talking about the old SQLITE and RFIDUI Folders? Nah, the imports should work since they are in the same directory. I had to move them to the same folder because it was easier to import functions from another .py file then having to figure out direct and relative directories.

In theory, we should be using the MainClient.py as our main file we should be running. So, if I can't import your function to the MainClient, I'll need to change a few things
